### PR TITLE
Fixes bug with duplicating case studies.

### PR DESCRIPTION
**Pull request by simaob**
- Includes data_layers in the cloning feature
- Skips file validation when cloning

### CODE REVIEW

**Comment by geriux** [comment]
Hi! Now it does duplicate the layers, but the project contacts, points of interest and images aren't getting duplicated.

**Comment by simaob** [comment]
Oh! OK =) I'll add those as well.

**Comment by simaob** [comment]
OK, I hope I haven't forgotten anything.

**Comment by geriux** [comment]
It's perfect now! Thankss!! 😁

**Pull request merged**
