### PR TITLE
Feature/case study raster

### PR DESCRIPTION
**Pull request by j8seangel**
Add raster support and include the https://github.com/Vizzuality/esaworld/pull/131 PR to fix the merge conflict

### CODE REVIEW

**Comment by simaob** [comment]
The loader should be spinning, no?

In FF 44 it stands still like in the image:

screen shot 2016-03-08 at 14 37 55

**Comment by simaob** [comment]
Text for "Raster Color Input" is not well spaced.
screen shot 2016-03-08 at 16 36 14

**Comment by apercas** [comment]
@simaob It was :( Maybe we've missed the `\n` in the placeholders ( @j8seangel  ?)

**Comment by simaob** [comment]
And just noticed that the spinner in firefox doesn't spin in at all. needs moar movement!

**Comment by simaob** [comment]
This raster support is pretty cool! :D

**Comment by apercas** [comment]
The `\n` is there https://github.com/Vizzuality/esaworld/blob/0f8ad4f6b59c1f7f2218040a22288d5fcdf7d589/app/views/backoffice/pages/_edit_form.html.slim#L78 https://github.com/Vizzuality/esaworld/blob/0f8ad4f6b59c1f7f2218040a22288d5fcdf7d589/app/views/backoffice/pages/_edit_form.html.slim#L78 I'll check Firefox support for that new line issue.

**Comment by simaob** [comment]
I was trying to upload a raster that doesn't work very well (it happened the same in WB), but CartoDB return: "state"=>"failure", when this happens. We should handle this. Update the status of that layer and inform the user somehow that the file they uploaded didn't work, for them to review it and try again.

And then there should be a way to either remove that Map page which failed or to start over.

Could you handle it as part of this PR? I can share the file that failed with you.

**Comment by j8seangel** [comment]
Done ! Also allow to remove the data_layer if the upload state failed.

**Comment by simaob** [comment]
I think you should add the error handling in `app/workers/carto_db_importer.rb` as well. If the raster faills to upload, there's no point in checking it 120 times. When you find that there's an error, just exit handle it straight away.

**Comment by j8seangel** [comment]
Change, thanks for the feedback !

**Comment by simaob** [comment]
Awesome :) well done

**Pull request merged**
