### PR TITLE
Set data_layers and charts

### PR DESCRIPTION
**Pull request by simaob**

### CODE REVIEW

**Comment by simaob** [comment]
I believe I've now fixed the issue with failing validations for map pages. Made some other improvements to the code on the controller and view.

**Comment by simaob** [comment]
Made a change that fixes it for updating a map page.
Only issue left is the CSS positioning of the fields. Could you have a look at it @j8seangel?
Basically:
1. Create new map page;
2. Edit map page and add a new layer without filling any of the fields for the new layer
3. press enter
4. see that the column selection is under the error layer (see screenshot)

screen shot 2016-02-12 at 15 56 29

**Comment by j8seangel** [comment]
It should be fixed in develop, so I'm going to merge and take the the look after.

**Comment by j8seangel** [comment]
Done! 

captura de pantalla 2016-02-12 a las 17 26 09

**Comment by simaob** [comment]
Nice :) :+1:

**Pull request merged**
